# .github/workflows/chromatic.yml
# https://www.chromatic.com/docs/github-actions

# Workflow name
name: 'Chromatic'

# Event for the workflow
on:
  push:
    branches:
      - main
    tags:
      - '!*' # Do not execute on tags
  pull_request:
    branches:
      - main
    # We want this action to run under specific pull request changes
    # opened: pull request is created
    # synchronize: commit(s) pushed to the pull request
    # reopened: closed pull request is reopened
    types: [opened, ready_for_review, synchronize, reopened]

# List of jobs
jobs:
  chromatic-deployment:
    if: ${{ github.actor != 'dependabot[bot]' && github.event.pull_request.draft == false }}
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        # Version 2 of the actions/checkout action will only checkout a single commit without history by default.
        # Chromatic needs the full git history in order to track changes over time.
        # see https://github.com/chromaui/action#:~:text=the%20Chromatic%20CLI-,Checkout,-depth
        with:
          fetch-depth: 0 # Required to retrieve git history
      - name: Install dependencies
        run: npm install
        # 👇 Adds Chromatic as a step in the workflow
      - name: Build and publish Storybook to Chromatic 🚀
        id: chromatic
        uses: chromaui/action@v1
        env:
          CHROMATIC_RETRIES: 3
        # Chromatic GitHub Action options
        with:
          buildScriptName: build-storybook
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }} # 👈 Chromatic projectToken, refer to the manage page to obtain it.
          token: ${{ secrets.GITHUB_TOKEN }}
          skip: 'dependabot/**'
          exitZeroOnChanges: github.ref != 'refs/heads/main' # 👈 Option to prevent the workflow from failing when changes are detected
          exitOnceUploaded: github.ref != 'refs/heads/main'
          autoAcceptChanges: github.ref == 'refs/heads/main' # 👈 Option to accept all changes when merging to master

      - name: Comment Storybook and Chromatic URL
        uses: actions/github-script@v3
        with:
          storybookUrl: ${{ steps.chromatic.outputs.storybookUrl}}
          buildUrl: ${{ steps.chromatic.outputs.buildUrl}}
          url: ${{ steps.chromatic.outputs.url}}
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const fs = require('fs')
            const ev = JSON.parse(
              fs.readFileSync(process.env.GITHUB_EVENT_PATH, 'utf8')
            )
            if(context.payload.pull_request) {
              await github.issues.createComment({
                issue_number: context.payload.pull_request.number,
                owner: context.payload.repository.owner.login,
                repo: context.payload.repository.name,
                body: `Build successful! 🎉
              * [View the storybook](${core.getInput('storybookUrl').replace('/iframe.html', '')})
              * [View the build](${core.getInput('buildUrl')})`
              })
            }
